<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Mapping;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countOpen()
    {
        $qb = $this->createQueryBuilder('t');

        return $qb
            ->select('count(t.id)')
            ->Where('t.closed = 0')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
